USE sanrio;

INSERT INTO PERSONAGENS (nome, aniv, descricao, url_img) VALUES
('Hello Kitty', '1960-11-01', 'A Hello Kitty é uma garota feliz e divertida, que adora espalhar alegria pelo mundo. Ela mora com seus pais e sua irmã gêmea, Mimmy,em Londres, na Inglaterra. Seu lema é: “Muitos amigos nunca são demais!” Por isso, ela está sempre cercada de amigos e adora fazer novas amizades.', 'https://www.sanrio.com.br/upload/eyJpdiI6ImhMRWU3YXE5eFgrR09URHI5K25RYUE9PSIsInZhbHVlIjoiYmlCY2pPemNXWEgyV1RaS0VHR1ZTUT09IiwibWFjIjoiMDJjY2M0NTc1YTVkZGZjMzBiYTUxMzFjYzZkMzMwY2Y2NGFkNjI5YmY1YWU5M2NmNTU1ZmE1MWVjOTBlYTFjMSJ9.png'),
('Keroppi', '1960-07-10', 'O Keroppi é um sapinho que mora com sua família em uma grande casa a beira do lago Donut. Ele e seus amigos adoram jogos, especialmente beisebol e bumerangue. Na maior parte do tempo, ele está com seu melhor amigo, a lesminha Denden.', 'https://www.sanrio.com.br/upload/eyJpdiI6IkJLOTN1Z1BmaWZ0RkM3WFFPZHFLaXc9PSIsInZhbHVlIjoibG5uN2ZtMTg3UlFjQ3B0TmxxaFwvZmc9PSIsIm1hYyI6ImM5NjQ4MTdlYTJlNzFkYWEwOThlOWUwYmNkZTU3ZDdkYTZhMDc2ZDZhNjdiNjEzYjcyYzAwNWFmZjA3NWE4YzIifQ==.png'),
('Chococat', '1960-05-10', 'O Chococat é um gatinho que pode parecer meio atrapalhado, mas está sempre por dentro das últimas novidades, graças aos seus bigodes antenados. Seu nome vem do seu focinho cor de chocolate.', 'https://www.sanrio.com.br/upload/eyJpdiI6IkUrYjFXWVc2TGtsME9VRU1KcDBnbVE9PSIsInZhbHVlIjoibUhqXC9WNmplXC9GS0d2OHpSWHVXdE5RPT0iLCJtYWMiOiJkMTViNTY5N2U5ZTJmNzBkNGU4OWJhYTkyNjU1ZjRlODJlY2M3ZTIxNzU4MzNjNGRmNDQxZjI3NThmNDEwNGE5In0=.png'),
('My Melody', '1960-01-18', 'A My Melody nasceu na floresta de Mary Land. Ela é super legal e faz amizade facilmente. Sua marca registrada é um lindo capuz, que sua avó costurou especialmente para ela.', 'https://www.sanrio.com.br/upload/eyJpdiI6InBDZjF1SzJpSFdEM1I2RWpQWGZreHc9PSIsInZhbHVlIjoiSW1vSGhNOUc4ZndWdFdSbEk3Mk9vZz09IiwibWFjIjoiZTE0YjhhYjA0OGRiYmQ5ZmI5ZDQwOGVkNDlmZmVjMTE1NDEwZDI4ZGU4MTRkZjEwY2VmYjliODY0ZmM4NjA5OSJ9.png'),
('Badtz Maru', '1960-04-01', 'O Badtz-Maru é um pinguim muito radical, que curte a sua vida “bem humorada” em Gorgeoustown. Ele atrai muita atenção quando anda com seu jacaré de estimação, o Pochi. E, também toca violino e piano, mas só finge, pois não é muito bom nisso.', 'https://www.sanrio.com.br/upload/eyJpdiI6Iks1b2hWSGx0WE1MRUdtYWlJZ1NSUEE9PSIsInZhbHVlIjoicTlWbmtHT21tWno0MFk3MGtEM0lBQT09IiwibWFjIjoiODVkNGVhZDc2MzU1YzJhMmIxOWE2MWViNzNlMGRhMmI2OGE5NzNjMjdjYjVjYTk3MTEzZTIyNWEzZGY3MmUzNSJ9.png'),
('Pompompurin', '1960-04-16', 'O Pompompurin é um tranquilo filhotinho Golden Retriever que tem um enorme talento para cochilar. Ele ama a frase “vamos sair”, tanto quanto odeia a palavra “ficar”. Faz amizade com todos que encontra, e tem um sonho de ser realmente grande. Seu hobby é colecionar os sapatos de seus donos e tem seu próprio esconderijo secreto.', 'https://www.sanrio.com.br/upload/eyJpdiI6IlpRU1NiSHU4MkRoakxINmNzTWdHRnc9PSIsInZhbHVlIjoiS1BpMklNam1ocTcxcHhNcTJuVVduUT09IiwibWFjIjoiYzU0ZGIyYzQzMzE3MWY3MThkNmIyOTQ0NjBlZTQ4ZWYxZWRiZDRjMjM0ODUxN2ZiZjc4ZjE4ZjVjY2M4MDQzOSJ9.png'),
('Kuromi', '1960-10-31', 'Kuromi é muito bagunceira e sempre causa confusões. Por trás de sua aparência radical, ela é super feminina. Adora escrever em seu diário e ler romances. Sua cor preferida é a preta. Ela é amiga da My Melody, mas encara essa amizade com uma certa competição.', 'https://www.sanrio.com.br/upload/eyJpdiI6IlE0WjNkVTJBQ2c4akxNb1NscjRtamc9PSIsInZhbHVlIjoiTEh6ZnlTc0NRbVVuMDR5TmZmUDBPQT09IiwibWFjIjoiNzk3MDMzNjRjMWIyYzE3ZDgyYmUzMmU5NDM1MTkyNTJkNGJlNGY3YjYyNTk1ZTI0MDBjMmMzNDg4MDQ3YWMwYiJ9.png'),
('Little Twin Stars', '1960-12-24', 'Kiki e Lala são pequenas estrelas gêmeas que nasceram na Constelação da Compaixão, na Galáxia dos Sonhos. Eles chegaram à Terra e espalham felicidade a todos que encontram pela frente.', 'https://www.sanrio.com.br/upload/eyJpdiI6InhwVVVrTjV2NDdtUk5cLzlDVFNaazFRPT0iLCJ2YWx1ZSI6IkxhdDhnR3JrSUdYcTA0QXFveTBGc2c9PSIsIm1hYyI6IjdkYmUxY2QyMmZiMzQxNTM2ZGI3MWE4MzgzMTI3NDAzOGRjMzZmOWVhNzQwY2NhMjJhYjk3MGQ4MjAzZmJiMjIifQ==.png'),
('Pochacco', '1960-02-29', 'O Pochacco é um carinha curioso e desajeitado, que às vezes mete o nariz onde não é chamado. Ele vive no Beco do Rouxinol e adora basquete, futebol e skate, por isso está sempre vestido com camisetas esportivas. Além disso, gosta de passear e ama sorvete de banana. Pelo fato de andar somente com as patas traseiras, ele está sempre batendo sua cabeça.', 'https://www.sanrio.com.br/upload/eyJpdiI6IkRkWlU3dVRwXC9pWXNJOWVhdVBJRGp3PT0iLCJ2YWx1ZSI6IlFUUHA5VzVoVG85QStvRzFGdUxwRkE9PSIsIm1hYyI6ImI0ODE3M2M1YWYyMWU5OTg5NWFiMWYxYTYzZmVjNmJkOTIyYjQyNDM2NDUxYzVlY2QxYmZjY2VmODQ2OGZhMjcifQ==.png'),
('Aggretsuko', '1960-11-06', 'Retsuko é uma panda vermelha de 25 anos, solteira e do signo de escorpião. Ela trabalha no departamento de contabilidade em uma grande empresa em Tóquio. Todos os dias ela pega metrô lotado e seu emprego é estressante, convive com colegas de trabalho que enchem sua paciência, seus chefes são antipáticos e dão a ela prazos curtos para entrega de seus afazeres. Para aliviar sua raiva ela canta Heavy Metal em um karaokê após o expediente.', 'https://www.sanrio.com.br/upload/eyJpdiI6IldGXC9oRUMwS0FuMmt5endjZ1ZmN3hBPT0iLCJ2YWx1ZSI6InU4czJjY1luS0U3MkNIWWVhNG1aaFE9PSIsIm1hYyI6IjQ4ODk2N2M5Y2NkOGQyMzI5MDQ5N2ZjOTA2OGI4MjA3ZTQ2YjU3NjFhOWNmYWNhMmIyMjU3ZjQ4N2E1MTJiZTcifQ==.png')
;